//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 47 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// Value: Number of added games
      ///
      /// Key: averageGames
      var averageGames: RswiftResources.StringResource { .init(key: "averageGames", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Average quantities players
      ///
      /// Key: averagePlayers
      var averagePlayers: RswiftResources.StringResource { .init(key: "averagePlayers", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Average game time
      ///
      /// Key: averageTime
      var averageTime: RswiftResources.StringResource { .init(key: "averageTime", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Back
      ///
      /// Key: back
      var back: RswiftResources.StringResource { .init(key: "back", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Basic cards
      ///
      /// Key: basicCards
      var basicCards: RswiftResources.StringResource { .init(key: "basicCards", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Cancel
      ///
      /// Key: cancel
      var cancel: RswiftResources.StringResource { .init(key: "cancel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Close
      ///
      /// Key: close
      var close: RswiftResources.StringResource { .init(key: "close", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Create
      ///
      /// Key: create
      var create: RswiftResources.StringResource { .init(key: "create", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Create game
      ///
      /// Key: createGame
      var createGame: RswiftResources.StringResource { .init(key: "createGame", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Create game
      ///
      /// Key: createGameLabel
      var createGameLabel: RswiftResources.StringResource { .init(key: "createGameLabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: There are no scheduled holidays for this day
      ///
      /// Key: createGameSublabel
      var createGameSublabel: RswiftResources.StringResource { .init(key: "createGameSublabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Delete
      ///
      /// Key: delete
      var delete: RswiftResources.StringResource { .init(key: "delete", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Do you really want to delete this?
      ///
      /// Key: deleteThis
      var deleteThis: RswiftResources.StringResource { .init(key: "deleteThis", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Edit
      ///
      /// Key: edit
      var edit: RswiftResources.StringResource { .init(key: "edit", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Edit game
      ///
      /// Key: editGame
      var editGame: RswiftResources.StringResource { .init(key: "editGame", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Edit statistics
      ///
      /// Key: editStatistics
      var editStatistics: RswiftResources.StringResource { .init(key: "editStatistics", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Enter favorite game
      ///
      /// Key: enterFavoriteGame
      var enterFavoriteGame: RswiftResources.StringResource { .init(key: "enterFavoriteGame", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Enter total quantity of hours for games
      ///
      /// Key: enterHoursGames
      var enterHoursGames: RswiftResources.StringResource { .init(key: "enterHoursGames", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Enter number of players
      ///
      /// Key: enterNumberPlayers
      var enterNumberPlayers: RswiftResources.StringResource { .init(key: "enterNumberPlayers", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Enter quantity of defeats
      ///
      /// Key: enterQuantityDefeats
      var enterQuantityDefeats: RswiftResources.StringResource { .init(key: "enterQuantityDefeats", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Enter quantity of wins
      ///
      /// Key: enterQuantityWins
      var enterQuantityWins: RswiftResources.StringResource { .init(key: "enterQuantityWins", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Enter rules
      ///
      /// Key: enterRules
      var enterRules: RswiftResources.StringResource { .init(key: "enterRules", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Favorite game
      ///
      /// Key: favoriteGame
      var favoriteGame: RswiftResources.StringResource { .init(key: "favoriteGame", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Game
      ///
      /// Key: game
      var game: RswiftResources.StringResource { .init(key: "game", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Game time
      ///
      /// Key: gameTime
      var gameTime: RswiftResources.StringResource { .init(key: "gameTime", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Game Time
      ///
      /// Key: gameTimeLabel
      var gameTimeLabel: RswiftResources.StringResource { .init(key: "gameTimeLabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Generate
      ///
      /// Key: generate
      var generate: RswiftResources.StringResource { .init(key: "generate", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Generator
      ///
      /// Key: generator
      var generator: RswiftResources.StringResource { .init(key: "generator", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Total quantity of hours for games
      ///
      /// Key: hoursGames
      var hoursGames: RswiftResources.StringResource { .init(key: "hoursGames", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Enter name game
      ///
      /// Key: nameGame
      var nameGame: RswiftResources.StringResource { .init(key: "nameGame", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Name Game
      ///
      /// Key: nameGameLabel
      var nameGameLabel: RswiftResources.StringResource { .init(key: "nameGameLabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: No data
      ///
      /// Key: noData
      var noData: RswiftResources.StringResource { .init(key: "noData", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Player Generator
      ///
      /// Key: playerGenerator
      var playerGenerator: RswiftResources.StringResource { .init(key: "playerGenerator", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: The player with number is selected
      ///
      /// Key: playerSelected
      var playerSelected: RswiftResources.StringResource { .init(key: "playerSelected", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Players
      ///
      /// Key: playersLabel
      var playersLabel: RswiftResources.StringResource { .init(key: "playersLabel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Quantities players
      ///
      /// Key: quantitiesPlayers
      var quantitiesPlayers: RswiftResources.StringResource { .init(key: "quantitiesPlayers", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Quantity of defeats
      ///
      /// Key: quantityDefeats
      var quantityDefeats: RswiftResources.StringResource { .init(key: "quantityDefeats", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Quantity of wins
      ///
      /// Key: quantityWins
      var quantityWins: RswiftResources.StringResource { .init(key: "quantityWins", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Rate app
      ///
      /// Key: rateApp
      var rateApp: RswiftResources.StringResource { .init(key: "rateApp", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Reset progress
      ///
      /// Key: reset
      var reset: RswiftResources.StringResource { .init(key: "reset", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Rules
      ///
      /// Key: rules
      var rules: RswiftResources.StringResource { .init(key: "rules", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Save
      ///
      /// Key: save
      var save: RswiftResources.StringResource { .init(key: "save", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Settings
      ///
      /// Key: settings
      var settings: RswiftResources.StringResource { .init(key: "settings", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Share app
      ///
      /// Key: shareApp
      var shareApp: RswiftResources.StringResource { .init(key: "shareApp", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Statistics
      ///
      /// Key: statistics
      var statistics: RswiftResources.StringResource { .init(key: "statistics", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Usage Policy
      ///
      /// Key: usagePolicy
      var usagePolicy: RswiftResources.StringResource { .init(key: "usagePolicy", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// Value: Value
      ///
      /// Key: value
      var value: RswiftResources.StringResource { .init(key: "value", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 61 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Card_1`.
    var card_1: RswiftResources.ImageResource { .init(name: "Card_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_10`.
    var card_10: RswiftResources.ImageResource { .init(name: "Card_10", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_12`.
    var card_12: RswiftResources.ImageResource { .init(name: "Card_12", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_13`.
    var card_13: RswiftResources.ImageResource { .init(name: "Card_13", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_14`.
    var card_14: RswiftResources.ImageResource { .init(name: "Card_14", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_15`.
    var card_15: RswiftResources.ImageResource { .init(name: "Card_15", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_16`.
    var card_16: RswiftResources.ImageResource { .init(name: "Card_16", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_17`.
    var card_17: RswiftResources.ImageResource { .init(name: "Card_17", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_18`.
    var card_18: RswiftResources.ImageResource { .init(name: "Card_18", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_19`.
    var card_19: RswiftResources.ImageResource { .init(name: "Card_19", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_2`.
    var card_2: RswiftResources.ImageResource { .init(name: "Card_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_20`.
    var card_20: RswiftResources.ImageResource { .init(name: "Card_20", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_21`.
    var card_21: RswiftResources.ImageResource { .init(name: "Card_21", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_22`.
    var card_22: RswiftResources.ImageResource { .init(name: "Card_22", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_23`.
    var card_23: RswiftResources.ImageResource { .init(name: "Card_23", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_24`.
    var card_24: RswiftResources.ImageResource { .init(name: "Card_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_25`.
    var card_25: RswiftResources.ImageResource { .init(name: "Card_25", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_26`.
    var card_26: RswiftResources.ImageResource { .init(name: "Card_26", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_27`.
    var card_27: RswiftResources.ImageResource { .init(name: "Card_27", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_28`.
    var card_28: RswiftResources.ImageResource { .init(name: "Card_28", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_29`.
    var card_29: RswiftResources.ImageResource { .init(name: "Card_29", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_3`.
    var card_3: RswiftResources.ImageResource { .init(name: "Card_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_30`.
    var card_30: RswiftResources.ImageResource { .init(name: "Card_30", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_31`.
    var card_31: RswiftResources.ImageResource { .init(name: "Card_31", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_32`.
    var card_32: RswiftResources.ImageResource { .init(name: "Card_32", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_33`.
    var card_33: RswiftResources.ImageResource { .init(name: "Card_33", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_34`.
    var card_34: RswiftResources.ImageResource { .init(name: "Card_34", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_35`.
    var card_35: RswiftResources.ImageResource { .init(name: "Card_35", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_36`.
    var card_36: RswiftResources.ImageResource { .init(name: "Card_36", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_37`.
    var card_37: RswiftResources.ImageResource { .init(name: "Card_37", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_38`.
    var card_38: RswiftResources.ImageResource { .init(name: "Card_38", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_39`.
    var card_39: RswiftResources.ImageResource { .init(name: "Card_39", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_4`.
    var card_4: RswiftResources.ImageResource { .init(name: "Card_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_40`.
    var card_40: RswiftResources.ImageResource { .init(name: "Card_40", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_41`.
    var card_41: RswiftResources.ImageResource { .init(name: "Card_41", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_42`.
    var card_42: RswiftResources.ImageResource { .init(name: "Card_42", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_43`.
    var card_43: RswiftResources.ImageResource { .init(name: "Card_43", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_44`.
    var card_44: RswiftResources.ImageResource { .init(name: "Card_44", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_45`.
    var card_45: RswiftResources.ImageResource { .init(name: "Card_45", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_46`.
    var card_46: RswiftResources.ImageResource { .init(name: "Card_46", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_47`.
    var card_47: RswiftResources.ImageResource { .init(name: "Card_47", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_48`.
    var card_48: RswiftResources.ImageResource { .init(name: "Card_48", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_49`.
    var card_49: RswiftResources.ImageResource { .init(name: "Card_49", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_5`.
    var card_5: RswiftResources.ImageResource { .init(name: "Card_5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_50`.
    var card_50: RswiftResources.ImageResource { .init(name: "Card_50", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_51`.
    var card_51: RswiftResources.ImageResource { .init(name: "Card_51", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_52`.
    var card_52: RswiftResources.ImageResource { .init(name: "Card_52", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_53`.
    var card_53: RswiftResources.ImageResource { .init(name: "Card_53", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_6`.
    var card_6: RswiftResources.ImageResource { .init(name: "Card_6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_7`.
    var card_7: RswiftResources.ImageResource { .init(name: "Card_7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_8`.
    var card_8: RswiftResources.ImageResource { .init(name: "Card_8", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Card_9`.
    var card_9: RswiftResources.ImageResource { .init(name: "Card_9", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `average_game_icon`.
    var average_game_icon: RswiftResources.ImageResource { .init(name: "average_game_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `average_players_icon`.
    var average_players_icon: RswiftResources.ImageResource { .init(name: "average_players_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `average_time_icon`.
    var average_time_icon: RswiftResources.ImageResource { .init(name: "average_time_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `game_arrow`.
    var game_arrow: RswiftResources.ImageResource { .init(name: "game_arrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `game_plus_icon`.
    var game_plus_icon: RswiftResources.ImageResource { .init(name: "game_plus_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `launch_main_image`.
    var launch_main_image: RswiftResources.ImageResource { .init(name: "launch_main_image", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_policy_icon`.
    var settings_policy_icon: RswiftResources.ImageResource { .init(name: "settings_policy_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_rate_icon`.
    var settings_rate_icon: RswiftResources.ImageResource { .init(name: "settings_rate_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `settings_share_icon`.
    var settings_share_icon: RswiftResources.ImageResource { .init(name: "settings_share_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
          }
        }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Game.plist`.
    var gamePlist: RswiftResources.FileResource { .init(name: "Game", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }
}